// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

namespace FlowChartWUI
{
    [default_interface]
    runtimeclass ColorDialogControl : Microsoft.UI.Xaml.Controls.UserControl
    {
        ColorDialogControl();
    }
}
