// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.220929.3

#pragma once
#ifndef WINRT_FlowChartWUI_0_H
#define WINRT_FlowChartWUI_0_H
WINRT_EXPORT namespace winrt::Microsoft::UI::Xaml::Markup
{
    struct IXamlMetadataProvider;
}
WINRT_EXPORT namespace winrt::FlowChartWUI
{
    struct IColorDialogControl;
    struct IMainWindow;
    struct ColorDialogControl;
    struct MainWindow;
    struct XamlMetaDataProvider;
}
namespace winrt::impl
{
    template <> struct category<winrt::FlowChartWUI::IColorDialogControl>{ using type = interface_category; };
    template <> struct category<winrt::FlowChartWUI::IMainWindow>{ using type = interface_category; };
    template <> struct category<winrt::FlowChartWUI::ColorDialogControl>{ using type = class_category; };
    template <> struct category<winrt::FlowChartWUI::MainWindow>{ using type = class_category; };
    template <> struct category<winrt::FlowChartWUI::XamlMetaDataProvider>{ using type = class_category; };
    template <> inline constexpr auto& name_v<winrt::FlowChartWUI::ColorDialogControl> = L"FlowChartWUI.ColorDialogControl";
    template <> inline constexpr auto& name_v<winrt::FlowChartWUI::MainWindow> = L"FlowChartWUI.MainWindow";
    template <> inline constexpr auto& name_v<winrt::FlowChartWUI::XamlMetaDataProvider> = L"FlowChartWUI.XamlMetaDataProvider";
    template <> inline constexpr auto& name_v<winrt::FlowChartWUI::IColorDialogControl> = L"FlowChartWUI.IColorDialogControl";
    template <> inline constexpr auto& name_v<winrt::FlowChartWUI::IMainWindow> = L"FlowChartWUI.IMainWindow";
    template <> inline constexpr guid guid_v<winrt::FlowChartWUI::IColorDialogControl>{ 0x6D5BB565,0x4A2B,0x5DCD,{ 0xBC,0xF2,0x20,0x6C,0x05,0xC7,0xF0,0x62 } }; // 6D5BB565-4A2B-5DCD-BCF2-206C05C7F062
    template <> inline constexpr guid guid_v<winrt::FlowChartWUI::IMainWindow>{ 0x5CEBCBFC,0x072A,0x5042,{ 0xB3,0xE5,0x3D,0x13,0x67,0x6B,0x20,0xA0 } }; // 5CEBCBFC-072A-5042-B3E5-3D13676B20A0
    template <> struct default_interface<winrt::FlowChartWUI::ColorDialogControl>{ using type = winrt::FlowChartWUI::IColorDialogControl; };
    template <> struct default_interface<winrt::FlowChartWUI::MainWindow>{ using type = winrt::FlowChartWUI::IMainWindow; };
    template <> struct default_interface<winrt::FlowChartWUI::XamlMetaDataProvider>{ using type = winrt::Microsoft::UI::Xaml::Markup::IXamlMetadataProvider; };
    template <> struct abi<winrt::FlowChartWUI::IColorDialogControl>
    {
        struct __declspec(novtable) type : inspectable_abi
        {
        };
    };
    template <> struct abi<winrt::FlowChartWUI::IMainWindow>
    {
        struct __declspec(novtable) type : inspectable_abi
        {
        };
    };
    template <typename D>
    struct consume_FlowChartWUI_IColorDialogControl
    {
    };
    template <> struct consume<winrt::FlowChartWUI::IColorDialogControl>
    {
        template <typename D> using type = consume_FlowChartWUI_IColorDialogControl<D>;
    };
    template <typename D>
    struct consume_FlowChartWUI_IMainWindow
    {
    };
    template <> struct consume<winrt::FlowChartWUI::IMainWindow>
    {
        template <typename D> using type = consume_FlowChartWUI_IMainWindow<D>;
    };
}
#endif
