// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.220929.3

#pragma once
#ifndef WINRT_FlowChartWUI_1_H
#define WINRT_FlowChartWUI_1_H
#include "winrt/impl/FlowChartWUI.0.h"
WINRT_EXPORT namespace winrt::FlowChartWUI
{
    struct __declspec(empty_bases) IColorDialogControl :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IColorDialogControl>
    {
        IColorDialogControl(std::nullptr_t = nullptr) noexcept {}
        IColorDialogControl(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IMainWindow :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IMainWindow>
    {
        IMainWindow(std::nullptr_t = nullptr) noexcept {}
        IMainWindow(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
