//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#pragma once


namespace winrt::FlowChartWUI::implementation
{
    using IInspectable = ::winrt::Windows::Foundation::IInspectable;

    template <typename D, typename ... I>
    struct ColorDialogControlT : public ::winrt::FlowChartWUI::implementation::ColorDialogControl_base<D,
        ::winrt::Microsoft::UI::Xaml::Markup::IComponentConnector,
        I...>
    {
        using base_type = typename ColorDialogControlT::base_type;
        using base_type::base_type;
        using class_type = typename ColorDialogControlT::class_type;

        void InitializeComponent();
        virtual void Connect(int32_t connectionId, IInspectable const& target);
        virtual ::winrt::Microsoft::UI::Xaml::Markup::IComponentConnector GetBindingConnector(int32_t connectionId, IInspectable const& target);
        void UnloadObject(::winrt::Microsoft::UI::Xaml::DependencyObject const& dependencyObject);
        void DisconnectUnloadedObject(int32_t connectionId);

        ::winrt::Microsoft::UI::Xaml::Controls::StackPanel pnlMain()
        {
            return _pnlMain;
        }
        void pnlMain(::winrt::Microsoft::UI::Xaml::Controls::StackPanel value)
        {
            _pnlMain = value;
        }
        
    protected:
        bool _contentLoaded{false};

    private:
        struct ColorDialogControl_obj1_Bindings;

        ::winrt::Microsoft::UI::Xaml::Controls::StackPanel _pnlMain{nullptr};
    };
}

