// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.220929.3

#pragma once
#include "winrt/FlowChartWUI.h"
#include "winrt/Microsoft.UI.Composition.h"
#include "winrt/Microsoft.UI.Xaml.h"
#include "winrt/Microsoft.UI.Xaml.Controls.h"
namespace winrt::FlowChartWUI::implementation
{
    template <typename D, typename... I>
    struct __declspec(empty_bases) ColorDialogControl_base : implements<D, FlowChartWUI::ColorDialogControl, composing, winrt::Microsoft::UI::Xaml::Controls::IControlOverrides, winrt::Microsoft::UI::Xaml::IFrameworkElementOverrides, winrt::Microsoft::UI::Xaml::IUIElementOverrides, I...>,
        impl::require<D, winrt::Microsoft::UI::Xaml::Controls::IUserControl, winrt::Microsoft::UI::Xaml::Controls::IControl, winrt::Microsoft::UI::Xaml::Controls::IControlProtected, winrt::Microsoft::UI::Xaml::IFrameworkElement, winrt::Microsoft::UI::Xaml::IFrameworkElementProtected, winrt::Microsoft::UI::Xaml::IUIElement, winrt::Microsoft::UI::Xaml::IUIElementProtected, winrt::Microsoft::UI::Composition::IAnimationObject, winrt::Microsoft::UI::Composition::IVisualElement, winrt::Microsoft::UI::Composition::IVisualElement2, winrt::Microsoft::UI::Xaml::IDependencyObject>,
        impl::base<D, winrt::Microsoft::UI::Xaml::Controls::UserControl, winrt::Microsoft::UI::Xaml::Controls::Control, winrt::Microsoft::UI::Xaml::FrameworkElement, winrt::Microsoft::UI::Xaml::UIElement, winrt::Microsoft::UI::Xaml::DependencyObject>,
        winrt::Microsoft::UI::Xaml::Controls::IControlOverridesT<D>, winrt::Microsoft::UI::Xaml::IFrameworkElementOverridesT<D>, winrt::Microsoft::UI::Xaml::IUIElementOverridesT<D>
    {
        using base_type = ColorDialogControl_base;
        using class_type = FlowChartWUI::ColorDialogControl;
        using implements_type = typename ColorDialogControl_base::implements_type;
        using implements_type::implements_type;
        using composable_base = winrt::Microsoft::UI::Xaml::Controls::UserControl;
        hstring GetRuntimeClassName() const
        {
            return L"FlowChartWUI.ColorDialogControl";
        }
        ColorDialogControl_base()
        {
            impl::call_factory<winrt::Microsoft::UI::Xaml::Controls::UserControl, winrt::Microsoft::UI::Xaml::Controls::IUserControlFactory>([&](winrt::Microsoft::UI::Xaml::Controls::IUserControlFactory const& f) { [[maybe_unused]] auto winrt_impl_discarded = f.CreateInstance(*this, this->m_inner); });
        }
    };
}
namespace winrt::FlowChartWUI::factory_implementation
{
    template <typename D, typename T, typename... I>
    struct __declspec(empty_bases) ColorDialogControlT : implements<D, winrt::Windows::Foundation::IActivationFactory, I...>
    {
        using instance_type = FlowChartWUI::ColorDialogControl;

        hstring GetRuntimeClassName() const
        {
            return L"FlowChartWUI.ColorDialogControl";
        }
        auto ActivateInstance() const
        {
            return make<T>();
        }
    };
}

#if defined(WINRT_FORCE_INCLUDE_COLORDIALOGCONTROL_XAML_G_H) || __has_include("ColorDialogControl.xaml.g.h")

#include "ColorDialogControl.xaml.g.h"

#else

namespace winrt::FlowChartWUI::implementation
{
    template <typename D, typename... I>
    using ColorDialogControlT = ColorDialogControl_base<D, I...>;
}

#endif
