// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.220929.3

void* winrt_make_FlowChartWUI_MainWindow()
{
    return winrt::detach_abi(winrt::make<winrt::FlowChartWUI::factory_implementation::MainWindow>());
}
WINRT_EXPORT namespace winrt::FlowChartWUI
{
    MainWindow::MainWindow() :
        MainWindow(make<FlowChartWUI::implementation::MainWindow>())
    {
    }
}
