//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#include "pch.h"
#include <memory>

#include "XamlTypeInfo.xaml.g.h"

#include "ColorDialogControl.xaml.h"
#include "App.xaml.h"
#include "MainWindow.xaml.h"
#include "XamlBindingInfo.xaml.g.hpp"
#include "ColorDialogControl.xaml.g.hpp"
#include "App.xaml.g.hpp"
#include "MainWindow.xaml.g.hpp"

namespace winrt::FlowChartWUI::implementation
{
using IXamlMember = ::winrt::Microsoft::UI::Xaml::Markup::IXamlMember;
using IXamlType = ::winrt::Microsoft::UI::Xaml::Markup::IXamlType;
using TypeKind = ::winrt::Windows::UI::Xaml::Interop::TypeKind;

template <typename T>
::winrt::Windows::Foundation::IInspectable ActivateType()
{
    return T();
}

template <typename T>
::winrt::Windows::Foundation::IInspectable ActivateLocalType()
{
    return ::winrt::make<T>();
}

template<typename TInstance, typename TItem>
void CollectionAdd(
    ::winrt::Windows::Foundation::IInspectable const& instance, 
    ::winrt::Windows::Foundation::IInspectable const& item)
{
    instance.as<TInstance>().Append(::winrt::unbox_value<TItem>(item));
}

template<typename TInstance, typename TKey, typename TItem>
void DictionaryAdd(
    ::winrt::Windows::Foundation::IInspectable const& instance,
    ::winrt::Windows::Foundation::IInspectable const& key,
    ::winrt::Windows::Foundation::IInspectable const& item)
{
    instance.as<TInstance>().Insert(::winrt::unbox_value<TKey>(key), ::winrt::unbox_value<TItem>(item));
}

template<typename T>
::winrt::Windows::Foundation::IInspectable FromStringConverter(
    XamlUserType const& userType, 
    ::winrt::hstring const& input)
{
    return ::winrt::box_value(static_cast<T>(userType.CreateEnumUIntFromString(input)));
}

template<typename TDeclaringType, typename TValue>
::winrt::Windows::Foundation::IInspectable GetValueTypeMember_UseCompactResources(::winrt::Windows::Foundation::IInspectable const& instance)
{
    return ::winrt::box_value<TValue>(instance.as<TDeclaringType>().UseCompactResources());
}

template<typename TDeclaringType, typename TValue>
::winrt::Windows::Foundation::IInspectable GetValueTypeMember_TabWidthMode(::winrt::Windows::Foundation::IInspectable const& instance)
{
    return ::winrt::box_value<TValue>(instance.as<TDeclaringType>().TabWidthMode());
}

template<typename TDeclaringType, typename TValue>
::winrt::Windows::Foundation::IInspectable GetValueTypeMember_SelectedIndex(::winrt::Windows::Foundation::IInspectable const& instance)
{
    return ::winrt::box_value<TValue>(instance.as<TDeclaringType>().SelectedIndex());
}

template<typename TDeclaringType, typename TValue>
::winrt::Windows::Foundation::IInspectable GetValueTypeMember_IsAddTabButtonVisible(::winrt::Windows::Foundation::IInspectable const& instance)
{
    return ::winrt::box_value<TValue>(instance.as<TDeclaringType>().IsAddTabButtonVisible());
}

template<typename TDeclaringType, typename TValue>
::winrt::Windows::Foundation::IInspectable GetValueTypeMember_CloseButtonOverlayMode(::winrt::Windows::Foundation::IInspectable const& instance)
{
    return ::winrt::box_value<TValue>(instance.as<TDeclaringType>().CloseButtonOverlayMode());
}

template<typename TDeclaringType, typename TValue>
::winrt::Windows::Foundation::IInspectable GetValueTypeMember_CanReorderTabs(::winrt::Windows::Foundation::IInspectable const& instance)
{
    return ::winrt::box_value<TValue>(instance.as<TDeclaringType>().CanReorderTabs());
}

template<typename TDeclaringType, typename TValue>
::winrt::Windows::Foundation::IInspectable GetValueTypeMember_CanDragTabs(::winrt::Windows::Foundation::IInspectable const& instance)
{
    return ::winrt::box_value<TValue>(instance.as<TDeclaringType>().CanDragTabs());
}

template<typename TDeclaringType, typename TValue>
::winrt::Windows::Foundation::IInspectable GetValueTypeMember_AllowDropTabs(::winrt::Windows::Foundation::IInspectable const& instance)
{
    return ::winrt::box_value<TValue>(instance.as<TDeclaringType>().AllowDropTabs());
}

template<typename TDeclaringType, typename TValue>
::winrt::Windows::Foundation::IInspectable GetValueTypeMember_IsClosable(::winrt::Windows::Foundation::IInspectable const& instance)
{
    return ::winrt::box_value<TValue>(instance.as<TDeclaringType>().IsClosable());
}

template <typename T>
::winrt::Windows::Foundation::IInspectable GetReferenceTypeStringMember_Title(::winrt::Windows::Foundation::IInspectable const& instance)
{
   return ::winrt::box_value(::winrt::Windows::Foundation::PropertyValue::CreateString(instance.as<T>().Title()));
}

template <typename T>
::winrt::Windows::Foundation::IInspectable GetReferenceTypeMember_TabItems(::winrt::Windows::Foundation::IInspectable const& instance)
{
    return ::winrt::box_value(instance.as<T>().TabItems());
}

template <typename T>
::winrt::Windows::Foundation::IInspectable GetReferenceTypeMember_TabStripHeader(::winrt::Windows::Foundation::IInspectable const& instance)
{
    return ::winrt::box_value(instance.as<T>().TabStripHeader());
}

template <typename T>
::winrt::Windows::Foundation::IInspectable GetReferenceTypeMember_TabStripFooter(::winrt::Windows::Foundation::IInspectable const& instance)
{
    return ::winrt::box_value(instance.as<T>().TabStripFooter());
}

template <typename T>
::winrt::Windows::Foundation::IInspectable GetReferenceTypeMember_TabStripHeaderTemplate(::winrt::Windows::Foundation::IInspectable const& instance)
{
    return ::winrt::box_value(instance.as<T>().TabStripHeaderTemplate());
}

template <typename T>
::winrt::Windows::Foundation::IInspectable GetReferenceTypeMember_TabStripFooterTemplate(::winrt::Windows::Foundation::IInspectable const& instance)
{
    return ::winrt::box_value(instance.as<T>().TabStripFooterTemplate());
}

template <typename T>
::winrt::Windows::Foundation::IInspectable GetReferenceTypeMember_TabItemsSource(::winrt::Windows::Foundation::IInspectable const& instance)
{
    return ::winrt::box_value(instance.as<T>().TabItemsSource());
}

template <typename T>
::winrt::Windows::Foundation::IInspectable GetReferenceTypeMember_TabItemTemplateSelector(::winrt::Windows::Foundation::IInspectable const& instance)
{
    return ::winrt::box_value(instance.as<T>().TabItemTemplateSelector());
}

template <typename T>
::winrt::Windows::Foundation::IInspectable GetReferenceTypeMember_TabItemTemplate(::winrt::Windows::Foundation::IInspectable const& instance)
{
    return ::winrt::box_value(instance.as<T>().TabItemTemplate());
}

template <typename T>
::winrt::Windows::Foundation::IInspectable GetReferenceTypeMember_SelectedItem(::winrt::Windows::Foundation::IInspectable const& instance)
{
    return ::winrt::box_value(instance.as<T>().SelectedItem());
}

template <typename T>
::winrt::Windows::Foundation::IInspectable GetReferenceTypeMember_AddTabButtonCommandParameter(::winrt::Windows::Foundation::IInspectable const& instance)
{
    return ::winrt::box_value(instance.as<T>().AddTabButtonCommandParameter());
}

template <typename T>
::winrt::Windows::Foundation::IInspectable GetReferenceTypeMember_AddTabButtonCommand(::winrt::Windows::Foundation::IInspectable const& instance)
{
    return ::winrt::box_value(instance.as<T>().AddTabButtonCommand());
}

template <typename T>
::winrt::Windows::Foundation::IInspectable GetReferenceTypeMember_Header(::winrt::Windows::Foundation::IInspectable const& instance)
{
    return ::winrt::box_value(instance.as<T>().Header());
}

template <typename T>
::winrt::Windows::Foundation::IInspectable GetReferenceTypeMember_IconSource(::winrt::Windows::Foundation::IInspectable const& instance)
{
    return ::winrt::box_value(instance.as<T>().IconSource());
}

template <typename T>
::winrt::Windows::Foundation::IInspectable GetReferenceTypeMember_HeaderTemplate(::winrt::Windows::Foundation::IInspectable const& instance)
{
    return ::winrt::box_value(instance.as<T>().HeaderTemplate());
}

template <typename T>
::winrt::Windows::Foundation::IInspectable GetReferenceTypeMember_TabViewTemplateSettings(::winrt::Windows::Foundation::IInspectable const& instance)
{
    return ::winrt::box_value(instance.as<T>().TabViewTemplateSettings());
}

template <typename T>
::winrt::Windows::Foundation::IInspectable GetReferenceTypeMember_Items(::winrt::Windows::Foundation::IInspectable const& instance)
{
    return ::winrt::box_value(instance.as<T>().Items());
}

template<typename TDeclaringType, typename TValue>
void SetEnumMember_TabWidthMode(
    ::winrt::Windows::Foundation::IInspectable const& instance, 
    ::winrt::Windows::Foundation::IInspectable const& value)
{
    instance.as<TDeclaringType>().TabWidthMode(::winrt::unbox_value<TValue>(value));
}

template<typename TDeclaringType, typename TValue>
void SetEnumMember_CloseButtonOverlayMode(
    ::winrt::Windows::Foundation::IInspectable const& instance, 
    ::winrt::Windows::Foundation::IInspectable const& value)
{
    instance.as<TDeclaringType>().CloseButtonOverlayMode(::winrt::unbox_value<TValue>(value));
}

template<typename TDeclaringType, typename TValue>
void SetValueTypeMember_UseCompactResources(
    ::winrt::Windows::Foundation::IInspectable const& instance, 
    ::winrt::Windows::Foundation::IInspectable const& value)
{
    instance.as<TDeclaringType>().UseCompactResources(::winrt::unbox_value<TValue>(value));
}

template<typename TDeclaringType, typename TValue>
void SetValueTypeMember_SelectedIndex(
    ::winrt::Windows::Foundation::IInspectable const& instance, 
    ::winrt::Windows::Foundation::IInspectable const& value)
{
    instance.as<TDeclaringType>().SelectedIndex(::winrt::unbox_value<TValue>(value));
}

template<typename TDeclaringType, typename TValue>
void SetValueTypeMember_IsAddTabButtonVisible(
    ::winrt::Windows::Foundation::IInspectable const& instance, 
    ::winrt::Windows::Foundation::IInspectable const& value)
{
    instance.as<TDeclaringType>().IsAddTabButtonVisible(::winrt::unbox_value<TValue>(value));
}

template<typename TDeclaringType, typename TValue>
void SetValueTypeMember_CanReorderTabs(
    ::winrt::Windows::Foundation::IInspectable const& instance, 
    ::winrt::Windows::Foundation::IInspectable const& value)
{
    instance.as<TDeclaringType>().CanReorderTabs(::winrt::unbox_value<TValue>(value));
}

template<typename TDeclaringType, typename TValue>
void SetValueTypeMember_CanDragTabs(
    ::winrt::Windows::Foundation::IInspectable const& instance, 
    ::winrt::Windows::Foundation::IInspectable const& value)
{
    instance.as<TDeclaringType>().CanDragTabs(::winrt::unbox_value<TValue>(value));
}

template<typename TDeclaringType, typename TValue>
void SetValueTypeMember_AllowDropTabs(
    ::winrt::Windows::Foundation::IInspectable const& instance, 
    ::winrt::Windows::Foundation::IInspectable const& value)
{
    instance.as<TDeclaringType>().AllowDropTabs(::winrt::unbox_value<TValue>(value));
}

template<typename TDeclaringType, typename TValue>
void SetValueTypeMember_IsClosable(
    ::winrt::Windows::Foundation::IInspectable const& instance, 
    ::winrt::Windows::Foundation::IInspectable const& value)
{
    instance.as<TDeclaringType>().IsClosable(::winrt::unbox_value<TValue>(value));
}

template<typename TDeclaringType, typename TValue>
void SetReferenceTypeStringMember_Title(
    ::winrt::Windows::Foundation::IInspectable const& instance, 
    ::winrt::Windows::Foundation::IInspectable const& value)
{
    return instance.as<TDeclaringType>().Title(::winrt::unbox_value<::winrt::hstring>(value));
}

template<typename TDeclaringType, typename TValue>
void SetReferenceTypeMember_TabStripHeader(
    ::winrt::Windows::Foundation::IInspectable const& instance, 
    ::winrt::Windows::Foundation::IInspectable const& value)
{
    instance.as<TDeclaringType>().TabStripHeader(value.as<TValue>());
}

template<typename TDeclaringType, typename TValue>
void SetReferenceTypeMember_TabStripFooter(
    ::winrt::Windows::Foundation::IInspectable const& instance, 
    ::winrt::Windows::Foundation::IInspectable const& value)
{
    instance.as<TDeclaringType>().TabStripFooter(value.as<TValue>());
}

template<typename TDeclaringType, typename TValue>
void SetReferenceTypeMember_TabStripHeaderTemplate(
    ::winrt::Windows::Foundation::IInspectable const& instance, 
    ::winrt::Windows::Foundation::IInspectable const& value)
{
    instance.as<TDeclaringType>().TabStripHeaderTemplate(value.as<TValue>());
}

template<typename TDeclaringType, typename TValue>
void SetReferenceTypeMember_TabStripFooterTemplate(
    ::winrt::Windows::Foundation::IInspectable const& instance, 
    ::winrt::Windows::Foundation::IInspectable const& value)
{
    instance.as<TDeclaringType>().TabStripFooterTemplate(value.as<TValue>());
}

template<typename TDeclaringType, typename TValue>
void SetReferenceTypeMember_TabItemsSource(
    ::winrt::Windows::Foundation::IInspectable const& instance, 
    ::winrt::Windows::Foundation::IInspectable const& value)
{
    instance.as<TDeclaringType>().TabItemsSource(value.as<TValue>());
}

template<typename TDeclaringType, typename TValue>
void SetReferenceTypeMember_TabItemTemplateSelector(
    ::winrt::Windows::Foundation::IInspectable const& instance, 
    ::winrt::Windows::Foundation::IInspectable const& value)
{
    instance.as<TDeclaringType>().TabItemTemplateSelector(value.as<TValue>());
}

template<typename TDeclaringType, typename TValue>
void SetReferenceTypeMember_TabItemTemplate(
    ::winrt::Windows::Foundation::IInspectable const& instance, 
    ::winrt::Windows::Foundation::IInspectable const& value)
{
    instance.as<TDeclaringType>().TabItemTemplate(value.as<TValue>());
}

template<typename TDeclaringType, typename TValue>
void SetReferenceTypeMember_SelectedItem(
    ::winrt::Windows::Foundation::IInspectable const& instance, 
    ::winrt::Windows::Foundation::IInspectable const& value)
{
    instance.as<TDeclaringType>().SelectedItem(value.as<TValue>());
}

template<typename TDeclaringType, typename TValue>
void SetReferenceTypeMember_AddTabButtonCommandParameter(
    ::winrt::Windows::Foundation::IInspectable const& instance, 
    ::winrt::Windows::Foundation::IInspectable const& value)
{
    instance.as<TDeclaringType>().AddTabButtonCommandParameter(value.as<TValue>());
}

template<typename TDeclaringType, typename TValue>
void SetReferenceTypeMember_AddTabButtonCommand(
    ::winrt::Windows::Foundation::IInspectable const& instance, 
    ::winrt::Windows::Foundation::IInspectable const& value)
{
    instance.as<TDeclaringType>().AddTabButtonCommand(value.as<TValue>());
}

template<typename TDeclaringType, typename TValue>
void SetReferenceTypeMember_Header(
    ::winrt::Windows::Foundation::IInspectable const& instance, 
    ::winrt::Windows::Foundation::IInspectable const& value)
{
    instance.as<TDeclaringType>().Header(value.as<TValue>());
}

template<typename TDeclaringType, typename TValue>
void SetReferenceTypeMember_IconSource(
    ::winrt::Windows::Foundation::IInspectable const& instance, 
    ::winrt::Windows::Foundation::IInspectable const& value)
{
    instance.as<TDeclaringType>().IconSource(value.as<TValue>());
}

template<typename TDeclaringType, typename TValue>
void SetReferenceTypeMember_HeaderTemplate(
    ::winrt::Windows::Foundation::IInspectable const& instance, 
    ::winrt::Windows::Foundation::IInspectable const& value)
{
    instance.as<TDeclaringType>().HeaderTemplate(value.as<TValue>());
}

enum TypeInfo_Flags
{
    TypeInfo_Flags_None                 = 0x00,
    TypeInfo_Flags_IsLocalType          = 0x01,
    TypeInfo_Flags_IsSystemType         = 0x02,
    TypeInfo_Flags_IsReturnTypeStub     = 0x04,
    TypeInfo_Flags_IsBindable           = 0x08,
    TypeInfo_Flags_IsMarkupExtension    = 0x10, 
};

struct TypeInfo
{
    const wchar_t* typeName{nullptr};
    const wchar_t* contentPropertyName{nullptr};
    ::winrt::Windows::Foundation::IInspectable (*activator)();
    void (*collectionAdd)(::winrt::Windows::Foundation::IInspectable const&, ::winrt::Windows::Foundation::IInspectable const&);
    void (*dictionaryAdd)(::winrt::Windows::Foundation::IInspectable const&, ::winrt::Windows::Foundation::IInspectable const&, ::winrt::Windows::Foundation::IInspectable const&);
    ::winrt::Windows::Foundation::IInspectable (*fromStringConverter)(XamlUserType const&, ::winrt::hstring const& );
    int     baseTypeIndex;
    int     firstMemberIndex;
    int     firstEnumValueIndex;
    int     createFromStringIndex;
    TypeKind kindOfType;
    unsigned int flags;
    int boxedTypeIndex;
};


const TypeInfo TypeInfos[] = 
{
    //   0
    L"Int32", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    0, 0, -1, TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    -1,
    //   1
    L"Object", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    0, 0, -1, TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    -1,
    //   2
    L"String", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    0, 0, -1, TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    -1,
    //   3
    L"Boolean", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    0, 0, -1, TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    -1,
    //   4
    L"System.Enum", L"",
    nullptr, nullptr, nullptr, nullptr,
    5, // System.ValueType
    0, 0, -1, TypeKind::Metadata,
    TypeInfo_Flags_None,
    -1,
    //   5
    L"System.ValueType", L"",
    nullptr, nullptr, nullptr, nullptr,
    1, // Object
    0, 0, -1, TypeKind::Metadata,
    TypeInfo_Flags_None,
    -1,
    //   6
    L"FlowChartWUI.MainWindow", L"",
    &ActivateLocalType<::winrt::FlowChartWUI::implementation::MainWindow>, nullptr, nullptr, nullptr,
    7, // Microsoft.UI.Xaml.Window
    0, 0, -1, TypeKind::Custom,
    TypeInfo_Flags_IsLocalType | TypeInfo_Flags_None,
    -1,
    //   7
    L"Microsoft.UI.Xaml.Window", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    0, 0, -1, TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    -1,
    //   8
    L"Microsoft.UI.Xaml.DataTemplate", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    0, 0, -1, TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    -1,
    //   9
    L"FlowChartWUI.ColorDialogControl", L"",
    &ActivateLocalType<::winrt::FlowChartWUI::implementation::ColorDialogControl>, nullptr, nullptr, nullptr,
    18, // Microsoft.UI.Xaml.Controls.UserControl
    0, 0, -1, TypeKind::Custom,
    TypeInfo_Flags_IsLocalType | TypeInfo_Flags_None,
    -1,
    //  10
    L"Microsoft.UI.Xaml.Input.ICommand", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    0, 0, -1, TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    -1,
    //  11
    L"Microsoft.UI.Xaml.Controls.Button", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    0, 0, -1, TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    -1,
    //  12
    L"Microsoft.UI.Xaml.Controls.TabView", L"Microsoft.UI.Xaml.Controls.TabView.TabItems",
    &ActivateType<::winrt::Microsoft::UI::Xaml::Controls::TabView>, nullptr, nullptr, nullptr,
    13, // Microsoft.UI.Xaml.Controls.Control
    0, 0, -1, TypeKind::Metadata,
    TypeInfo_Flags_None,
    -1,
    //  13
    L"Microsoft.UI.Xaml.Controls.Control", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    18, 0, -1, TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    -1,
    //  14
    L"Microsoft.UI.Xaml.DependencyObject", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    18, 0, -1, TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    -1,
    //  15
    L"Microsoft.UI.Xaml.Controls.MenuBar", L"Microsoft.UI.Xaml.Controls.MenuBar.Items",
    &ActivateType<::winrt::Microsoft::UI::Xaml::Controls::MenuBar>, nullptr, nullptr, nullptr,
    13, // Microsoft.UI.Xaml.Controls.Control
    18, 0, -1, TypeKind::Metadata,
    TypeInfo_Flags_None,
    -1,
    //  16
    L"Microsoft.UI.Xaml.ResourceDictionary", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    19, 0, -1, TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    -1,
    //  17
    L"Microsoft.UI.Xaml.Controls.IconSource", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    19, 0, -1, TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    -1,
    //  18
    L"Microsoft.UI.Xaml.Controls.UserControl", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    19, 0, -1, TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    -1,
    //  19
    L"Microsoft.UI.Xaml.Controls.TabViewItem", L"",
    &ActivateType<::winrt::Microsoft::UI::Xaml::Controls::TabViewItem>, nullptr, nullptr, nullptr,
    21, // Microsoft.UI.Xaml.Controls.ListViewItem
    19, 0, -1, TypeKind::Metadata,
    TypeInfo_Flags_None,
    -1,
    //  20
    L"Microsoft.UI.Xaml.Controls.MenuBarItem", L"Microsoft.UI.Xaml.Controls.MenuBarItem.Items",
    &ActivateType<::winrt::Microsoft::UI::Xaml::Controls::MenuBarItem>, nullptr, nullptr, nullptr,
    13, // Microsoft.UI.Xaml.Controls.Control
    24, 0, -1, TypeKind::Metadata,
    TypeInfo_Flags_None,
    -1,
    //  21
    L"Microsoft.UI.Xaml.Controls.ListViewItem", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    26, 0, -1, TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    -1,
    //  22
    L"Microsoft.UI.Xaml.Controls.ContentControl", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    26, 0, -1, TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    -1,
    //  23
    L"Microsoft.UI.Xaml.Controls.DropDownButton", L"",
    &ActivateType<::winrt::Microsoft::UI::Xaml::Controls::DropDownButton>, nullptr, nullptr, nullptr,
    11, // Microsoft.UI.Xaml.Controls.Button
    26, 0, -1, TypeKind::Metadata,
    TypeInfo_Flags_None,
    -1,
    //  24
    L"Microsoft.UI.Xaml.Controls.TabViewWidthMode", L"",
    nullptr, nullptr, nullptr, &FromStringConverter<::winrt::Microsoft::UI::Xaml::Controls::TabViewWidthMode>,
    4, // System.Enum
    26, 0, -1, TypeKind::Metadata,
    TypeInfo_Flags_None,
    -1,
    //  25
    L"Microsoft.UI.Xaml.Controls.MenuFlyoutItemBase", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    26, 3, -1, TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    -1,
    //  26
    L"Microsoft.UI.Xaml.Controls.DataTemplateSelector", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    26, 3, -1, TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    -1,
    //  27
    L"Microsoft.UI.Xaml.Controls.XamlControlsResources", L"",
    &ActivateType<::winrt::Microsoft::UI::Xaml::Controls::XamlControlsResources>, nullptr, &DictionaryAdd<::winrt::Microsoft::UI::Xaml::Controls::XamlControlsResources, ::winrt::Windows::Foundation::IInspectable, ::winrt::Windows::Foundation::IInspectable>, nullptr,
    16, // Microsoft.UI.Xaml.ResourceDictionary
    26, 3, -1, TypeKind::Metadata,
    TypeInfo_Flags_None,
    -1,
    //  28
    L"Windows.Foundation.Collections.IVector`1<Object>", L"",
    nullptr, &CollectionAdd<::winrt::Windows::Foundation::Collections::IVector<::winrt::Windows::Foundation::IInspectable>, ::winrt::Windows::Foundation::IInspectable>, nullptr, nullptr,
    -1,
    27, 3, -1, TypeKind::Metadata,
    TypeInfo_Flags_IsReturnTypeStub | TypeInfo_Flags_None,
    -1,
    //  29
    L"Microsoft.UI.Xaml.Controls.TabViewItemTemplateSettings", L"",
    nullptr, nullptr, nullptr, nullptr,
    14, // Microsoft.UI.Xaml.DependencyObject
    27, 3, -1, TypeKind::Metadata,
    TypeInfo_Flags_IsReturnTypeStub | TypeInfo_Flags_None,
    -1,
    //  30
    L"Microsoft.UI.Xaml.Controls.TabViewCloseButtonOverlayMode", L"",
    nullptr, nullptr, nullptr, &FromStringConverter<::winrt::Microsoft::UI::Xaml::Controls::TabViewCloseButtonOverlayMode>,
    4, // System.Enum
    27, 3, -1, TypeKind::Metadata,
    TypeInfo_Flags_None,
    -1,
    //  31
    L"Windows.Foundation.Collections.IVector`1<Microsoft.UI.Xaml.Controls.MenuBarItem>", L"",
    nullptr, &CollectionAdd<::winrt::Windows::Foundation::Collections::IVector<::winrt::Microsoft::UI::Xaml::Controls::MenuBarItem>, ::winrt::Microsoft::UI::Xaml::Controls::MenuBarItem>, nullptr, nullptr,
    -1,
    27, 6, -1, TypeKind::Metadata,
    TypeInfo_Flags_IsReturnTypeStub | TypeInfo_Flags_None,
    -1,
    //  32
    L"Windows.Foundation.Collections.IVector`1<Microsoft.UI.Xaml.Controls.MenuFlyoutItemBase>", L"",
    nullptr, &CollectionAdd<::winrt::Windows::Foundation::Collections::IVector<::winrt::Microsoft::UI::Xaml::Controls::MenuFlyoutItemBase>, ::winrt::Microsoft::UI::Xaml::Controls::MenuFlyoutItemBase>, nullptr, nullptr,
    -1,
    27, 6, -1, TypeKind::Metadata,
    TypeInfo_Flags_IsReturnTypeStub | TypeInfo_Flags_None,
    -1,
    //  Last type here is for padding
    L"", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1, 
    27, 6, -1, TypeKind::Custom,
    TypeInfo_Flags_None,
};

constexpr uint32_t TypeInfoLookup[] = { 
      0,   //   0
      0,   //   1
      0,   //   2
      0,   //   3
      0,   //   4
      0,   //   5
      1,   //   6
      3,   //   7
      4,   //   8
      4,   //   9
      4,   //  10
      4,   //  11
      5,   //  12
      5,   //  13
      5,   //  14
      5,   //  15
      5,   //  16
      6,   //  17
      6,   //  18
      6,   //  19
      6,   //  20
      6,   //  21
      6,   //  22
      6,   //  23
      7,   //  24
      8,   //  25
      8,   //  26
      8,   //  27
      8,   //  28
      8,   //  29
      8,   //  30
      9,   //  31
     10,   //  32
     11,   //  33
     12,   //  34
     16,   //  35
     16,   //  36
     17,   //  37
     18,   //  38
     21,   //  39
     22,   //  40
     22,   //  41
     24,   //  42
     24,   //  43
     25,   //  44
     25,   //  45
     26,   //  46
     26,   //  47
     27,   //  48
     29,   //  49
     29,   //  50
     29,   //  51
     29,   //  52
     29,   //  53
     29,   //  54
     30,   //  55
     30,   //  56
     31,   //  57
     31,   //  58
     31,   //  59
     31,   //  60
     31,   //  61
     31,   //  62
     31,   //  63
     31,   //  64
     31,   //  65
     31,   //  66
     31,   //  67
     31,   //  68
     31,   //  69
     31,   //  70
     31,   //  71
     31,   //  72
     31,   //  73
     31,   //  74
     31,   //  75
     31,   //  76
     31,   //  77
     31,   //  78
     31,   //  79
     31,   //  80
     32,   //  81
     32,   //  82
     32,   //  83
     32,   //  84
     32,   //  85
     32,   //  86
     32,   //  87
     33,   //  88
};

struct EnumValueInfo
{
    const wchar_t* name{nullptr};
    int eValue;
};

const EnumValueInfo EnumValues[] =
{ 
    L"Equal", static_cast<int>(::winrt::Microsoft::UI::Xaml::Controls::TabViewWidthMode::Equal),
    L"SizeToContent", static_cast<int>(::winrt::Microsoft::UI::Xaml::Controls::TabViewWidthMode::SizeToContent),
    L"Compact", static_cast<int>(::winrt::Microsoft::UI::Xaml::Controls::TabViewWidthMode::Compact),
    L"Auto", static_cast<int>(::winrt::Microsoft::UI::Xaml::Controls::TabViewCloseButtonOverlayMode::Auto),
    L"OnPointerOver", static_cast<int>(::winrt::Microsoft::UI::Xaml::Controls::TabViewCloseButtonOverlayMode::OnPointerOver),
    L"Always", static_cast<int>(::winrt::Microsoft::UI::Xaml::Controls::TabViewCloseButtonOverlayMode::Always),
};

struct MemberInfo 
{
    const wchar_t* shortName{nullptr};
    ::winrt::Windows::Foundation::IInspectable (*getter)(::winrt::Windows::Foundation::IInspectable const&);
    void (*setter)(::winrt::Windows::Foundation::IInspectable const&, ::winrt::Windows::Foundation::IInspectable const&);
    int typeIndex;
    int targetTypeIndex;
    bool isReadOnly;
    bool isDependencyProperty;
    bool isAttachable;
};

const MemberInfo MemberInfos[] = 
{
    //   0 - Microsoft.UI.Xaml.Controls.TabView.TabItems
    L"TabItems",
    &GetReferenceTypeMember_TabItems<::winrt::Microsoft::UI::Xaml::Controls::TabView>,
    nullptr,
    28, // Windows.Foundation.Collections.IVector`1<Object>
    -1,
    true,  true,  false,
    //   1 - Microsoft.UI.Xaml.Controls.TabView.TabStripHeader
    L"TabStripHeader",
    &GetReferenceTypeMember_TabStripHeader<::winrt::Microsoft::UI::Xaml::Controls::TabView>,
    &SetReferenceTypeMember_TabStripHeader<::winrt::Microsoft::UI::Xaml::Controls::TabView, ::winrt::Windows::Foundation::IInspectable>,
    1, // Object
    -1,
    false, true,  false,
    //   2 - Microsoft.UI.Xaml.Controls.TabView.TabStripFooter
    L"TabStripFooter",
    &GetReferenceTypeMember_TabStripFooter<::winrt::Microsoft::UI::Xaml::Controls::TabView>,
    &SetReferenceTypeMember_TabStripFooter<::winrt::Microsoft::UI::Xaml::Controls::TabView, ::winrt::Windows::Foundation::IInspectable>,
    1, // Object
    -1,
    false, true,  false,
    //   3 - Microsoft.UI.Xaml.Controls.TabView.TabWidthMode
    L"TabWidthMode",
    &GetValueTypeMember_TabWidthMode<::winrt::Microsoft::UI::Xaml::Controls::TabView, ::winrt::Microsoft::UI::Xaml::Controls::TabViewWidthMode>,
    &SetEnumMember_TabWidthMode<::winrt::Microsoft::UI::Xaml::Controls::TabView, ::winrt::Microsoft::UI::Xaml::Controls::TabViewWidthMode>,
    24, // Microsoft.UI.Xaml.Controls.TabViewWidthMode
    -1,
    false, true,  false,
    //   4 - Microsoft.UI.Xaml.Controls.TabView.TabStripHeaderTemplate
    L"TabStripHeaderTemplate",
    &GetReferenceTypeMember_TabStripHeaderTemplate<::winrt::Microsoft::UI::Xaml::Controls::TabView>,
    &SetReferenceTypeMember_TabStripHeaderTemplate<::winrt::Microsoft::UI::Xaml::Controls::TabView, ::winrt::Microsoft::UI::Xaml::DataTemplate>,
    8, // Microsoft.UI.Xaml.DataTemplate
    -1,
    false, true,  false,
    //   5 - Microsoft.UI.Xaml.Controls.TabView.TabStripFooterTemplate
    L"TabStripFooterTemplate",
    &GetReferenceTypeMember_TabStripFooterTemplate<::winrt::Microsoft::UI::Xaml::Controls::TabView>,
    &SetReferenceTypeMember_TabStripFooterTemplate<::winrt::Microsoft::UI::Xaml::Controls::TabView, ::winrt::Microsoft::UI::Xaml::DataTemplate>,
    8, // Microsoft.UI.Xaml.DataTemplate
    -1,
    false, true,  false,
    //   6 - Microsoft.UI.Xaml.Controls.TabView.TabItemsSource
    L"TabItemsSource",
    &GetReferenceTypeMember_TabItemsSource<::winrt::Microsoft::UI::Xaml::Controls::TabView>,
    &SetReferenceTypeMember_TabItemsSource<::winrt::Microsoft::UI::Xaml::Controls::TabView, ::winrt::Windows::Foundation::IInspectable>,
    1, // Object
    -1,
    false, true,  false,
    //   7 - Microsoft.UI.Xaml.Controls.TabView.TabItemTemplateSelector
    L"TabItemTemplateSelector",
    &GetReferenceTypeMember_TabItemTemplateSelector<::winrt::Microsoft::UI::Xaml::Controls::TabView>,
    &SetReferenceTypeMember_TabItemTemplateSelector<::winrt::Microsoft::UI::Xaml::Controls::TabView, ::winrt::Microsoft::UI::Xaml::Controls::DataTemplateSelector>,
    26, // Microsoft.UI.Xaml.Controls.DataTemplateSelector
    -1,
    false, true,  false,
    //   8 - Microsoft.UI.Xaml.Controls.TabView.TabItemTemplate
    L"TabItemTemplate",
    &GetReferenceTypeMember_TabItemTemplate<::winrt::Microsoft::UI::Xaml::Controls::TabView>,
    &SetReferenceTypeMember_TabItemTemplate<::winrt::Microsoft::UI::Xaml::Controls::TabView, ::winrt::Microsoft::UI::Xaml::DataTemplate>,
    8, // Microsoft.UI.Xaml.DataTemplate
    -1,
    false, true,  false,
    //   9 - Microsoft.UI.Xaml.Controls.TabView.SelectedItem
    L"SelectedItem",
    &GetReferenceTypeMember_SelectedItem<::winrt::Microsoft::UI::Xaml::Controls::TabView>,
    &SetReferenceTypeMember_SelectedItem<::winrt::Microsoft::UI::Xaml::Controls::TabView, ::winrt::Windows::Foundation::IInspectable>,
    1, // Object
    -1,
    false, true,  false,
    //  10 - Microsoft.UI.Xaml.Controls.TabView.SelectedIndex
    L"SelectedIndex",
    &GetValueTypeMember_SelectedIndex<::winrt::Microsoft::UI::Xaml::Controls::TabView, int32_t>,
    &SetValueTypeMember_SelectedIndex<::winrt::Microsoft::UI::Xaml::Controls::TabView, int32_t>,
    0, // Int32
    -1,
    false, true,  false,
    //  11 - Microsoft.UI.Xaml.Controls.TabView.IsAddTabButtonVisible
    L"IsAddTabButtonVisible",
    &GetValueTypeMember_IsAddTabButtonVisible<::winrt::Microsoft::UI::Xaml::Controls::TabView, bool>,
    &SetValueTypeMember_IsAddTabButtonVisible<::winrt::Microsoft::UI::Xaml::Controls::TabView, bool>,
    3, // Boolean
    -1,
    false, true,  false,
    //  12 - Microsoft.UI.Xaml.Controls.TabView.CloseButtonOverlayMode
    L"CloseButtonOverlayMode",
    &GetValueTypeMember_CloseButtonOverlayMode<::winrt::Microsoft::UI::Xaml::Controls::TabView, ::winrt::Microsoft::UI::Xaml::Controls::TabViewCloseButtonOverlayMode>,
    &SetEnumMember_CloseButtonOverlayMode<::winrt::Microsoft::UI::Xaml::Controls::TabView, ::winrt::Microsoft::UI::Xaml::Controls::TabViewCloseButtonOverlayMode>,
    30, // Microsoft.UI.Xaml.Controls.TabViewCloseButtonOverlayMode
    -1,
    false, true,  false,
    //  13 - Microsoft.UI.Xaml.Controls.TabView.CanReorderTabs
    L"CanReorderTabs",
    &GetValueTypeMember_CanReorderTabs<::winrt::Microsoft::UI::Xaml::Controls::TabView, bool>,
    &SetValueTypeMember_CanReorderTabs<::winrt::Microsoft::UI::Xaml::Controls::TabView, bool>,
    3, // Boolean
    -1,
    false, true,  false,
    //  14 - Microsoft.UI.Xaml.Controls.TabView.CanDragTabs
    L"CanDragTabs",
    &GetValueTypeMember_CanDragTabs<::winrt::Microsoft::UI::Xaml::Controls::TabView, bool>,
    &SetValueTypeMember_CanDragTabs<::winrt::Microsoft::UI::Xaml::Controls::TabView, bool>,
    3, // Boolean
    -1,
    false, true,  false,
    //  15 - Microsoft.UI.Xaml.Controls.TabView.AllowDropTabs
    L"AllowDropTabs",
    &GetValueTypeMember_AllowDropTabs<::winrt::Microsoft::UI::Xaml::Controls::TabView, bool>,
    &SetValueTypeMember_AllowDropTabs<::winrt::Microsoft::UI::Xaml::Controls::TabView, bool>,
    3, // Boolean
    -1,
    false, true,  false,
    //  16 - Microsoft.UI.Xaml.Controls.TabView.AddTabButtonCommandParameter
    L"AddTabButtonCommandParameter",
    &GetReferenceTypeMember_AddTabButtonCommandParameter<::winrt::Microsoft::UI::Xaml::Controls::TabView>,
    &SetReferenceTypeMember_AddTabButtonCommandParameter<::winrt::Microsoft::UI::Xaml::Controls::TabView, ::winrt::Windows::Foundation::IInspectable>,
    1, // Object
    -1,
    false, true,  false,
    //  17 - Microsoft.UI.Xaml.Controls.TabView.AddTabButtonCommand
    L"AddTabButtonCommand",
    &GetReferenceTypeMember_AddTabButtonCommand<::winrt::Microsoft::UI::Xaml::Controls::TabView>,
    &SetReferenceTypeMember_AddTabButtonCommand<::winrt::Microsoft::UI::Xaml::Controls::TabView, ::winrt::Microsoft::UI::Xaml::Input::ICommand>,
    10, // Microsoft.UI.Xaml.Input.ICommand
    -1,
    false, true,  false,
    //  18 - Microsoft.UI.Xaml.Controls.MenuBar.Items
    L"Items",
    &GetReferenceTypeMember_Items<::winrt::Microsoft::UI::Xaml::Controls::MenuBar>,
    nullptr,
    31, // Windows.Foundation.Collections.IVector`1<Microsoft.UI.Xaml.Controls.MenuBarItem>
    -1,
    true,  true,  false,
    //  19 - Microsoft.UI.Xaml.Controls.TabViewItem.Header
    L"Header",
    &GetReferenceTypeMember_Header<::winrt::Microsoft::UI::Xaml::Controls::TabViewItem>,
    &SetReferenceTypeMember_Header<::winrt::Microsoft::UI::Xaml::Controls::TabViewItem, ::winrt::Windows::Foundation::IInspectable>,
    1, // Object
    -1,
    false, true,  false,
    //  20 - Microsoft.UI.Xaml.Controls.TabViewItem.IsClosable
    L"IsClosable",
    &GetValueTypeMember_IsClosable<::winrt::Microsoft::UI::Xaml::Controls::TabViewItem, bool>,
    &SetValueTypeMember_IsClosable<::winrt::Microsoft::UI::Xaml::Controls::TabViewItem, bool>,
    3, // Boolean
    -1,
    false, true,  false,
    //  21 - Microsoft.UI.Xaml.Controls.TabViewItem.IconSource
    L"IconSource",
    &GetReferenceTypeMember_IconSource<::winrt::Microsoft::UI::Xaml::Controls::TabViewItem>,
    &SetReferenceTypeMember_IconSource<::winrt::Microsoft::UI::Xaml::Controls::TabViewItem, ::winrt::Microsoft::UI::Xaml::Controls::IconSource>,
    17, // Microsoft.UI.Xaml.Controls.IconSource
    -1,
    false, true,  false,
    //  22 - Microsoft.UI.Xaml.Controls.TabViewItem.HeaderTemplate
    L"HeaderTemplate",
    &GetReferenceTypeMember_HeaderTemplate<::winrt::Microsoft::UI::Xaml::Controls::TabViewItem>,
    &SetReferenceTypeMember_HeaderTemplate<::winrt::Microsoft::UI::Xaml::Controls::TabViewItem, ::winrt::Microsoft::UI::Xaml::DataTemplate>,
    8, // Microsoft.UI.Xaml.DataTemplate
    -1,
    false, true,  false,
    //  23 - Microsoft.UI.Xaml.Controls.TabViewItem.TabViewTemplateSettings
    L"TabViewTemplateSettings",
    &GetReferenceTypeMember_TabViewTemplateSettings<::winrt::Microsoft::UI::Xaml::Controls::TabViewItem>,
    nullptr,
    29, // Microsoft.UI.Xaml.Controls.TabViewItemTemplateSettings
    -1,
    true,  true,  false,
    //  24 - Microsoft.UI.Xaml.Controls.MenuBarItem.Items
    L"Items",
    &GetReferenceTypeMember_Items<::winrt::Microsoft::UI::Xaml::Controls::MenuBarItem>,
    nullptr,
    32, // Windows.Foundation.Collections.IVector`1<Microsoft.UI.Xaml.Controls.MenuFlyoutItemBase>
    -1,
    true,  true,  false,
    //  25 - Microsoft.UI.Xaml.Controls.MenuBarItem.Title
    L"Title",
    &GetReferenceTypeStringMember_Title<::winrt::Microsoft::UI::Xaml::Controls::MenuBarItem>,
    &SetReferenceTypeStringMember_Title<::winrt::Microsoft::UI::Xaml::Controls::MenuBarItem, ::winrt::hstring>,
    2, // String
    -1,
    false, true,  false,
    //  26 - Microsoft.UI.Xaml.Controls.XamlControlsResources.UseCompactResources
    L"UseCompactResources",
    &GetValueTypeMember_UseCompactResources<::winrt::Microsoft::UI::Xaml::Controls::XamlControlsResources, bool>,
    &SetValueTypeMember_UseCompactResources<::winrt::Microsoft::UI::Xaml::Controls::XamlControlsResources, bool>,
    3, // Boolean
    -1,
    false, true,  false,
};

const wchar_t* GetShortName(const wchar_t* longName)
{
    const auto separator = wcsrchr(longName, '.');
    return separator ? separator + 1: longName;
}

const TypeInfo* GetTypeInfo(::winrt::hstring const& typeName)
{
    size_t typeNameLength = typeName.size();
    if (typeNameLength < _countof(TypeInfoLookup) - 1)
    {
        const auto begin = TypeInfos + TypeInfoLookup[typeNameLength];
        const auto end = TypeInfos + TypeInfoLookup[typeNameLength + 1];
        auto pos = std::find_if(begin, end, [&typeName](TypeInfo const& elem)
        {
            return wcscmp(typeName.data(), elem.typeName) == 0;
        });
        if (pos != end)
        {
            return pos;
        }
    }
    return nullptr;
}

const MemberInfo* GetMemberInfo(::winrt::hstring const& longMemberName)
{
    const auto dotPosition = std::find(longMemberName.crbegin(), longMemberName.crend(), L'.').base();
    if (dotPosition != longMemberName.end())
    {
        const auto sizeBeforeDot = static_cast<::winrt::hstring::size_type>(dotPosition - longMemberName.begin()) - 1;
        const TypeInfo* pTypeInfo = GetTypeInfo(::winrt::hstring{longMemberName.data(), sizeBeforeDot});
        if (pTypeInfo)
        {
            const TypeInfo* pNextTypeInfo = pTypeInfo + 1;
            const auto shortMemberName = GetShortName(longMemberName.data());
            const auto begin = MemberInfos + pTypeInfo->firstMemberIndex;
            const auto end = MemberInfos + pNextTypeInfo->firstMemberIndex;
            auto info = std::find_if(begin, end,
                [shortMemberName](const MemberInfo& elem)
            {
                return wcscmp(shortMemberName, elem.shortName) == 0;
            });
            if (info != end)
            {
                return info;
            }
        }
    }
    return nullptr;
}

std::vector<::winrt::Microsoft::UI::Xaml::Markup::IXamlMetadataProvider> const& XamlTypeInfoProvider::OtherProviders()
{
    std::lock_guard<std::recursive_mutex> lock(_xamlTypesCriticalSection);
    if (_otherProviders.empty())
    {
        _otherProviders.push_back(::winrt::Microsoft::UI::Xaml::XamlTypeInfo::XamlControlsXamlMetaDataProvider());
    }
    return _otherProviders;
}

IXamlType XamlTypeInfoProvider::CreateXamlType(::winrt::hstring const& typeName)
{
    const TypeInfo* pTypeInfo = GetTypeInfo(typeName);
    const TypeInfo* pNextTypeInfo = pTypeInfo + 1;
    if (!pTypeInfo || !pNextTypeInfo)
    {
        return nullptr;
    }
    else if (pTypeInfo->flags & TypeInfo_Flags_IsSystemType)
    {
        return ::winrt::make<XamlSystemBaseType>(typeName);
    }
    else
    {
        ::winrt::hstring baseName { pTypeInfo->baseTypeIndex >= 0 ? TypeInfos[pTypeInfo->baseTypeIndex].typeName : L""};
        ::winrt::hstring boxedName { pTypeInfo->boxedTypeIndex >= 0 ? TypeInfos[pTypeInfo->boxedTypeIndex].typeName : L""};
        auto userType = ::winrt::make_self<XamlUserType>(shared_from_this(), pTypeInfo->typeName, GetXamlTypeByName(baseName));
        userType->_kindOfType = pTypeInfo->kindOfType;
        userType->_activator = pTypeInfo->activator;
        userType->_collectionAdd = pTypeInfo->collectionAdd;
        userType->_dictionaryAdd = pTypeInfo->dictionaryAdd;
        userType->_fromStringConverter = pTypeInfo->fromStringConverter;
        userType->ContentPropertyName(pTypeInfo->contentPropertyName);
        userType->IsLocalType(pTypeInfo->flags & TypeInfo_Flags_IsLocalType);
        userType->IsReturnTypeStub(pTypeInfo->flags & TypeInfo_Flags_IsReturnTypeStub);
        userType->IsBindable(pTypeInfo->flags & TypeInfo_Flags_IsBindable);
        userType->IsMarkupExtension(pTypeInfo->flags & TypeInfo_Flags_IsMarkupExtension);
        userType->_createFromStringMethod = nullptr;
        userType->SetBoxedType(GetXamlTypeByName(boxedName));
        for (int i = pTypeInfo->firstMemberIndex; i < pNextTypeInfo->firstMemberIndex; ++i)
        {
            userType->AddMemberName(MemberInfos[i].shortName);
        }
        for (int i = pTypeInfo->firstEnumValueIndex; i < pNextTypeInfo->firstEnumValueIndex; ++i)
        {
            userType->AddEnumValue(EnumValues[i].name, winrt::Windows::Foundation::PropertyValue::CreateInt32(EnumValues[i].eValue));
        }
        return userType.as<IXamlType>();
    }
}

IXamlMember XamlTypeInfoProvider::CreateXamlMember(::winrt::hstring const& longMemberName)
{
    const MemberInfo* pMemberInfo = GetMemberInfo(longMemberName);
    if (!pMemberInfo)
    {
        return nullptr;
    }
    auto xamlMember = ::winrt::make_self<XamlMember>(shared_from_this(),
        pMemberInfo->shortName, TypeInfos[pMemberInfo->typeIndex].typeName);
    xamlMember->_getter = pMemberInfo->getter;
    xamlMember->_setter = pMemberInfo->setter;
    xamlMember->TargetTypeName(pMemberInfo->targetTypeIndex >= 0 ? TypeInfos[pMemberInfo->targetTypeIndex].typeName : L"");
    xamlMember->IsReadOnly(pMemberInfo->isReadOnly);
    xamlMember->IsDependencyProperty(pMemberInfo->isDependencyProperty);
    xamlMember->IsAttachable(pMemberInfo->isAttachable);

    return xamlMember.as<IXamlMember>();
}
} // namespace
