// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.220929.3

#pragma once
#ifndef WINRT_FlowChartWUI_H
#define WINRT_FlowChartWUI_H
#include "winrt/base.h"
static_assert(winrt::check_version(CPPWINRT_VERSION, "2.0.220929.3"), "Mismatched C++/WinRT headers.");
#define CPPWINRT_VERSION "2.0.220929.3"
#include "winrt/impl/Microsoft.UI.Composition.2.h"
#include "winrt/impl/Microsoft.UI.Xaml.2.h"
#include "winrt/impl/Microsoft.UI.Xaml.Controls.2.h"
#include "winrt/impl/Microsoft.UI.Xaml.Markup.2.h"
#include "winrt/impl/FlowChartWUI.2.h"
namespace winrt::impl
{
    template <typename D>
    struct produce<D, winrt::FlowChartWUI::IColorDialogControl> : produce_base<D, winrt::FlowChartWUI::IColorDialogControl>
    {
    };
    template <typename D>
    struct produce<D, winrt::FlowChartWUI::IMainWindow> : produce_base<D, winrt::FlowChartWUI::IMainWindow>
    {
    };
}
WINRT_EXPORT namespace winrt::FlowChartWUI
{
}
namespace std
{
#ifndef WINRT_LEAN_AND_MEAN
    template<> struct hash<winrt::FlowChartWUI::IColorDialogControl> : winrt::impl::hash_base {};
    template<> struct hash<winrt::FlowChartWUI::IMainWindow> : winrt::impl::hash_base {};
    template<> struct hash<winrt::FlowChartWUI::ColorDialogControl> : winrt::impl::hash_base {};
    template<> struct hash<winrt::FlowChartWUI::MainWindow> : winrt::impl::hash_base {};
    template<> struct hash<winrt::FlowChartWUI::XamlMetaDataProvider> : winrt::impl::hash_base {};
#endif
#ifdef __cpp_lib_format
#endif
}
#endif
